Update misleading error message
The mcelog package is only shipped for x86_64. When the package fails to
install on other architectures we should report that setup failed
due to the missing package.

On aarch64 the test setup failure currently looks like this:

    Installing mcelog ...

    Last metadata expiration check: 0:04:01 ago on Wed 31 May 2023 11:26:47 AM EDT.
    No match for argument: mcelog
    Error: Unable to find a match: mcelog
    :: [ 11:30:49 ] :: [  FATAL   ] :: test setup failed, some of git clone failed...
    :: [ 11:30:49 ] :: [   FAIL   ] :: test setup failed, some of git clone failed... (Assert: expected 0, got 1)

Signed-off-by: Eddie Kovsky <ekovsky@redhat.com>