process/trinity_git: add extra CFLAGS for gcc-14+
Sine gcc-14, the implicit declarition would break the compile process by
default. Add the change to workaround the compile issue.

$[trinity]  ./configure  | grep memfd_create
[*] Checking if glibc provides memfd_create.. [NO]
[trinity]$ make | grep memfd_create
fds/memfd.c:22:12: error: static declaration of ‘memfd_create’ follows non-static declaration
   22 | static int memfd_create(__unused__ const char *uname, __unused__ unsigned int flag)
      |            ^~~~~~~~~~~~
In file included from /usr/include/bits/mman-linux.h:116,
                 from /usr/include/bits/mman.h:38,
                 from /usr/include/sys/mman.h:41,
                 from fds/memfd.c:8:
/usr/include/bits/mman-shared.h:55:5: note: previous declaration of ‘memfd_create’ with type ‘int(const char *, unsigned int)’
   55 | int memfd_create (const char *__name, unsigned int __flags) __THROW;
      |     ^~~~~~~~~~~~
make: *** [Makefile:113: fds/memfd.o] Error 1

Signed-off-by: Chunyu Hu <chuhu@redhat.com>