integrity: 1896046 fix signing rpm failure
Resolves: https://issues.redhat.com/browse/RHEL-50626

Currently the test fails with the following errors,

    spawn rpmsign --verbose --addsign --signfiles --fskpath privkey_evm.pem signfiles-1-1.noarch.rpm
    signfiles-1-1.noarch.rpm:
    hash(sha256): e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    evm/ima signature: 136 bytes
    hash(sha256): 4fbcc3a083d4c0efbb420f400ec2b50ca2df53f358e60694e2350f292bd11893
    evm/ima signature: 136 bytes
    hash(sha256): 4fbcc3a083d4c0efbb420f400ec2b50ca2df53f358e60694e2350f292bd11893
    evm/ima signature: 136 bytes
    hash(sha256): 3b6a07d0d404fab4e23b6d34bc6696a6a312dd92821332385e5af7c01c421351
    evm/ima signature: 136 bytes
    gpg: signing failed: No such file or directory
    gpg: signing failed: No such file or directory
    error: gpg exec failed (2)
    expect: spawn id exp3 not open
        while executing
    "expect eof"
        (file "sign.exp" line 13)

expect doesn't seem to be robust to pass the passphrase to gpg. So
use empty password to avoid feeding passpharse into gpg.

Signed-off-by: Coiby Xu <coiby.xu@gmail.com>